### ISSUE TITLE
Invalid Plugin.yml

### ISSUE THREAD

**Issue by MctomSpdo** [JamCoreModding/right-click-harvest#29]
While loading the plugin, the following Error occured: 

> [12:00:44] [Server thread/ERROR]: Could not load 'plugins/right-click-harvest-3.1.0+1.19.4.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
>         at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:179) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:157) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) ~[paper-1.19.3.jar:git-Paper-372]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-372]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-372]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-372]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
>         ... 7 more

Plugin Version: 3.1.0
Plugin file name: right-click-harvest-3.1.0+1.19.4.jar
Server Software: PaperMc
Minecraft Version: 1.19.3
Paper Build: #448

Downloaded from the official [Curseforge site](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest/files) 

Since I will be updating my Server very soon, I will also try on the newest 1.19.4 build and report back.

**Comment by Jamalam360** [comment]
This is a Fabric mod, not a plugin

**Comment by MctomSpdo** [comment]
Oh my yeah, sorry, there is also a plugin named the exact same
