### ISSUE TITLE
Add option to multiply the amount of hunger used per crop harvested

### ISSUE THREAD

**Issue by James103** [JamCoreModding/right-click-harvest#31]
Currently, when the config option "Use Hunger" is enabled, every time a player uses a hoe to harvest a crop, there is a 50% chance that action costs ≈0.4 hunger (for an average cost of ≈0.2 hunger per crop harvested).

This effectively means a player can only harvest around 64-100 wheat with a hoe before needing to eat, which is very low by Minecraft standards.

For comparison, a player can mine 800 blocks, that is harvest 10 9x9 plots of wheat with their fist (or any other tool) before losing a single food point. Even if placing a block also cost 1/800 food point, a player could still harvest and replant 400 m<sup>2</sup> of a crop field per food point (4400 m<sup>2</sup> per bread with saturation).

A workaround would be to just use a higher tier hoe, as an iron hoe harvests up to 5 crops and a diamond hoe 9. <strike>Even this would be less efficient than just breaking and replanting a crop manually, at 26 and 69 m<sup>2</sup> per food point respectively (around 290 and 760 m<sup>2</sup> per bread with saturation)</strike> Edit: My original calculations were incorrect here; a single use of a Diamond Hoe costs up to 1.8 hunger on average as each of the 9 crops harvested has that 50% chance to cost 0.2 hunger. Therefore, regardless of the hoe used, a player can right-click-harvest only _5.3_ m<sup>2</sup> of a crop per food point (59 m<sup>2</sup> per bread with saturation)

Therefore, I would like if a config option was added to adjust the exact amount of hunger used every time harvesting crops with a hoe costs hunger, in order to make the food costs more balanced with respect to vanilla.

**Comment by Jamalam360** [comment]
I can add a config at some point, thank you
