### ISSUE TITLE
Config option `hungerLevel` (exhaustion per crop harvested) limited to 3 discrete values

### ISSUE THREAD

**Issue by James103** [JamCoreModding/right-click-harvest#33]
Commit bd44f55135c17748fe4157e0cd5548228357b8bc adds an option to configure the amount of hunger used for each block when right-click harvesting; however, that config seems to be limited to three discrete values: `LOW` = 0.0025, `NORMAL` = 0.005 and `HIGH` = 0.0075. For some pack makers, none of these suit the intended playstyle.

Is it possible to insert a number in place of these three words, multiplying the exhaustion per crop harvest (`0.005`) by said number? If not, could that be implemented?

Current workaround: download the mod source, edit the enum at line 46 of `src/main/java/io/github/jamalam360/rightclickharvest/config/Config.java`, then recompile from the modified source, place the resulting file in the server's mod folder and change `NORMAL` in `hungerLevel = NORMAL` in the mod's config file as appropriate.
https://github.com/JamCoreModding/right-click-harvest/blob/92fcf0e9bcffb8dad9de63652b7b9ebca72e23b6/src/main/java/io/github/jamalam360/rightclickharvest/config/Config.java#L46-L48

**Comment by Jamalam360** [comment]
I'm generally wary of providing number inputs rather than enums, what value are you wanting to use?

**Comment by James103** [comment]
For example, I would like to have the `HIGH` value be `2.0f` instead of `1.5f` to fully account for the cost of replanting the crop, assuming placing blocks (including planting crops) costs the same amount of exhaustion as breaking blocks or including more of the cost of running a second full pass over the field to replant.

**Comment by Jamalam360** [comment]
OK, I can increase the high values.
