### ISSUE TITLE
[1.18.2 fml] Cannot right-click harvest Enchanced Farming veggies

### ISSUE THREAD

**Issue by Cixon** [JamCoreModding/right-click-harvest#36]
mod incompat: https://www.curseforge.com/minecraft/mc-mods/enhanced-farming

**Comment by Cixon** [comment]
at least in the wild... i also have Wildplants 3 and attempting to do this on farm that were generated on grassblocks did not result in a successful harvest.

Wildplants 3
https://www.curseforge.com/minecraft/mc-mods/wks-wildplants/screenshots

**Comment by Jamalam360** [comment]
Just to make sure, since the enhanced farming one should work, how are you trying to harvest the crops? It may be the case that you're trying to harvest without holding a hoe, in which case you'll need to change the `requiresHoe` config to false.

**Comment by Cixon** [comment]
> Just to make sure, since the enhanced farming one should work, how are you trying to harvest the crops? It may be the case that you're trying to harvest without holding a hoe, in which case you'll need to change the `requiresHoe` config to false.

I am using a hoe. To be more specific, a iron hoe. The mod doesn't allow harvest on anything other than farmland. With Wildplants 3, that mod randomly generates crops and some land on blocks other than grassblocks.

**Comment by Jamalam360** [comment]
No, there's no check that the crop is on top of farmland. Looking into this

**Comment by Jamalam360** [comment]
So Wildplants is using `FlowerBlock` rather than `CropBlock`. I'm unsure of the limitations incurred by having to generate the blocks using world generation, but it is just asking for mod compatibility issues by not using the Minecraft `CropBlock` and having a custom wheat block.

**Comment by Cixon** [comment]
> So Wildplants is using `FlowerBlock` rather than `CropBlock`. I'm unsure of the limitations incurred by having to generate the blocks using world generation, but it is just asking for mod compatibility issues by not using the Minecraft `CropBlock` and having a custom wheat block.

I see. So in order for it to register to RCH’s system it must be registered under Minecraft’s registry, right? If so I can open a ticket to request this

**Comment by Jamalam360** [comment]
Not exactly. You can copy and paste the following and say it's from me, and I'll come and join the issue if you link it back here.

> Wildplants seems to place its own custom wheat block that extends `FlowerBlock` rather than using vanillas wheat block. I don't know if this is required for worldgen purposes, but it causes problems with mod compatibility since any mod looking for a `CropBlock` or `Blocks.WHEAT` is not going to work with wildplants out of the box.
