### ISSUE TITLE
Invalid Icon for Fabric Mod Menu

### ISSUE THREAD

**Issue by Giacomino99** [JamCoreModding/right-click-harvest#37]
Right-Click-Harvest's icon (icon.png) is 800x801px in size. Currently, when looking at the menu, the following message appears in the log:

> [14:12:04] [Render thread/WARN]: Warning! Mod rightclickharvest has a broken icon, loading default icon

For an icon to work with Mod Menu and properly display is must be a perfect square. I can confirm that reducing the height of the image by one pixel fixes the issue and displays properly in-game.

**Comment by Jamalam360** [comment]
Oh right, that logo was from BisectHostings partner graphic design team, thanks for reporting
