### ISSUE TITLE
Config Info

### ISSUE THREAD

**Issue by Unleashed75** [JamCoreModding/right-click-harvest#38]
There is a lack of info in the config.
It's mentioned in the Read Me that;
"Configure if a hoe is required and whether harvesting uses hunger points."
"Configure whether higher tier hoes harvest in a larger radius."

I only see

"requireHoe": true/false"
I guess it's only true or false based on what was already here but does it have more options?

"harvestInRadius": true/false"
again, I guess it's only true or false based on what was already here but does false mean it will harvest in a square?
Can I give it a number to change the size of the radius?

"hungerLevel": "NORMAL"
I have no idea on the options for this.

Where is the config for "whether higher tier hoes harvest in a larger radius"?
harvestInRadius and higherTierHoesHarvest sound like different options to me.

All of this info would be nice to have in the config or even in the Read Me.
Thanks for the mod

**Comment by Jamalam360** [comment]
Explained in the documentation.

https://docs.jamalam.tech/right-click-harvest/configuration/#config-options

**Comment by Unleashed75** [comment]
Only reading the Closed issues, have I found
hungerLevel is LOW, NORMAL, HIGH
As for the Tier idea someone gave. The ranges for each type doesn't fit right with me.

There are 6 tiers of tools, in order;
Wood, Stone, Iron, Diamond, Netherite, Gold.
I feel Wood and stone should do a 1x1
Iron 2x2
Diamond 3x3
Netherite 4x4
Gold 5x5
fyi, gold has always been the fastest tool for mining but also has the lowest durability.
While I could see gold doing 2x2. These new ranges feel more fitting.
If added, I hope to see info in the config what True or False values give you and how each tool has a different range.

**Comment by Jamalam360** [comment]
There is nothing to be 'added', this is all already documented and advertised in the 'Read the Documentation' badge.

You can [configure the hoe tiers yourself](https://docs.jamalam.tech/right-click-harvest/developers/tags) with a datapack.

**Comment by Unleashed75** [comment]
The amount of times I have looked on the Read Me page and missed the documentation link. Soz

I would like to still see a little more info in the configs though.

If you are using tags like low,mid,high_tier_hoes
Then seeing these options in the config would makes more sense than an extra datapack.
I don't make datapacks and finding one to do just this one thing will be impossible.
You have the setting there already within the mod, let use use it without the need for datapacks and if datapacks need to use it, let them override any setting we put.

I know it's not as simple as that but still...
anyway. I feel like you may not want to but the configs still need to show the options I think or have the link

**Comment by Jamalam360** [comment]
JSON cannot have comments (without just having a field called `__comment` or something), and most users will just be editing it via mod menu which has descriptions.

Datapack makes sense because it's referring to items, the tag system is perfectly suited to this where storing item IDs in a config file is not
