### ISSUE TITLE
[1.20.1 Forge] Doesn't work

### ISSUE THREAD

**Issue by manchyy** [JamCoreModding/right-click-harvest#43]
I have tested it on vanilla crops (wheat, carrot) and it doesn't work.

Canola crops *do* harvest, but I'm not sure whether the Ultimate Car Mod has that functionality built in for their own crops.

**Comment by Jamalam360** [comment]
You probably need to change `./config/rightclickharvest.json` or use the in game config editor.

`requireHoe` should be `false` for what you are expecting. Feel free to reopen if necessary
