### ISSUE TITLE
area harvest not working on every plant

### ISSUE THREAD

**Issue by dziczekparniczek** [JamCoreModding/right-click-harvest#44]
I noticed that when harvesting with right mouse button and having hoe in a hand some vanilla plants (like potates and carrots) get harvested singly while others from Farmer's Delight mod are harvestable in area 3x3

**Comment by Jamalam360** [comment]
Please send your config and the type of hoe you were using so I can investigate this

**Comment by Jamalam360** [comment]
I can't reproduce this, but the latest update will bring changes to the hoe required system that may improve mod compatibility
