### ISSUE TITLE
(1.19.2-forge) Right click does not harvest wheat

### ISSUE THREAD

**Issue by Dj-Polyester** [JamCoreModding/right-click-harvest#45]
I am playing minecraft 1.19.2 and right click doesn't do anything on wheat. I haven't tried other crops yet.
I loaded all mods with forge. List of the mods I am currently using:
```
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.5.85-forge.jar
corpse-1.19.2-1.0.0.jar
ftb-chunks-forge-1902.4.1-build.290.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-teams-forge-1902.2.14-build.123.jar
ftb-ultimine-forge-1902.4.1-build.90.jar
jei-1.19.2-forge-11.6.0.1016.jar
right-click-harvest-3.2.0+1.19.2-forge.jar
theoneprobe-1.19-6.2.2.jar
```
Thanks for developing the mod and thanks for future replies.

**Comment by Jamalam360** [comment]
Common issue:

1. Are you using a hoe?
2. If not, and you want it to work without a hoe: change the config either using a GUI (mod menu on Fabric, the mods screen on Forge), or at `config/rightclicharvest.json`
3. If yes, there is probably another issue and I can diagnose further

**Comment by Dj-Polyester** [comment]
Thank you for the fast reply. Sorry I replied late. I was trying to configure that boolean you mentioned. I did it and worked. For those who want to configure without modifying jar files (forge doesn't support config for newer versions) I suggest [configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod. Closing the issue.
