### ISSUE TITLE
right click doesnt work

### ISSUE THREAD

**Issue by jaaloley** [JamCoreModding/right-click-harvest#46]
when i rightclick on crops, i hear a sound that something should be happening but nothing happens

**Comment by Jamalam360** [comment]
1. Are you using a hoe?
2. If not, and you want it to work without a hoe: change the config either using a GUI (mod menu on Fabric, the mods screen on Forge), or at config/rightclicharvest.json
3. If yes, there is probably another issue and I can diagnose further

**Comment by Jamalam360** [comment]
Closing for now, please reopen if the above doesn't solve your issue

**Comment by jaaloley** [comment]
Tried using it without a hoe, then with a hoe because I read about it. Still didn’t work. Then changed it to without a hoe (changed it in the settings by using mod menu to view them and then checked in the file) and it still didn’t work, no matter if I use a hoe or not. I do have a few other (client-side) mods (im playing on a server if that maybe stops it from working). But none of them messes with the crops so it should work

**Comment by Jamalam360** [comment]
Yes it is required to be installed on the server as well

**Comment by jaaloley** [comment]
Oh okay, that solves it, thanks a lot
