### ISSUE TITLE
[Fabric] Incompatible with Supplementaries Flax

### ISSUE THREAD

**Issue by Shibva** [JamCoreModding/right-click-harvest#47]
The issue is straigtforward

Right-click on a crop that operates like the flax from Supplementary and it will not preserve the crop if done on the uppermost part of it (it will work though if done on the lowermost however)

**Comment by Jamalam360** [comment]
What's the flax from supplementary like?

**Comment by Shibva** [comment]
A one block crop that's growth is apart of 2 blocks; ![image](https://github.com/JamCoreModding/right-click-harvest/assets/38770780/a80a1053-05ba-4f57-8cb2-7c8b0b7066c2)

Right click in the harvest of a top section will not properly "replant" the section that doesn't even however if you do, it's the bottom section it works as intended

**Comment by Shibva** [comment]
(Image was from google; not at my computer to take a proper photo)

**Comment by Jamalam360** [comment]
Sorry it's been a while. I can test and fix this once Supplementaries updates to 1.20.2

**Comment by Shibva** [comment]
It's been around its even In the 19.2 version as well

**Comment by Jamalam360** [comment]
I'm only maintaining 1.20.2 for now

**Comment by Jamalam360** [comment]
I've ended up making a standalone compatibility mod (there are a few reasons it couldn't be built in to either mods). I'll send the link here once I publish it. It's for 1.20.1, but I might test it with 1.19.2 and mark it as compatible if it works
