### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Rezpect264** [JamCoreModding/right-click-harvest#51]
Config doen't work. I change it and nothing happens . 
This is how it looks like after i changed it.
{
  "requireHoe": false,
  "harvestInRadius": true,
  "hungerLevel": "NONE"
}

**Comment by Rezpect264** [comment]
Mod works on Sugar cant doesnt require hoe , but on wheat it does

**Comment by Jamalam360** [comment]
Can't reproduce this

**Comment by Jamalam360** [comment]
Feel free to reopen if you still have this issue
