### ISSUE TITLE
[Fabric 1.20.1] Cannot stack sugarcane more than 3 blocks tall

### ISSUE THREAD

**Issue by TheRealWormbo** [JamCoreModding/right-click-harvest#52]
Using the default configuration, which requires a hoe to harvest crops, any right-click on a sugarcane plant that is at least three blocks high will break it even while not holding a hoe. I can place sugarcane against non-sugarcane blocks fine to achieve the stacking, but if I accidentally right-click a sugarcane block directly (from the side), the entire thing breaks down to height 1.

There are legitimate decorative or functional reasons to stack sugarcane manually, and sometimes it's easier to do that by placing it against the side of another sugarcane block, so this feature ignoring the hoe requirement is quite a problem when trying to make walls out of that plant.

**Comment by Jamalam360** [comment]
RightClickHarvest now won't work if the player is crouching, hopefully that solves your issue.
