### ISSUE TITLE
[Fabric] Game Crashes with Error `java.lang.RuntimeException` on Launch

### ISSUE THREAD

**Issue by allmightychaos** [JamCoreModding/right-click-harvest#53]
**Fabric Version**: 0.14.24
**Minecraft / Mod Version**: 1.20.2

---

Whenever launching the game, it immediately crashes on startup, and returns me the error stated in the title:
_`java.lang.RuntimeException`: Could not execute entrypoint stage `main `due to errors, provided by `rightclickharvest`_

Here is the logfile Minecraft gave me, if that helps. 
[rightclickharvest-error.txt](https://github.com/JamCoreModding/right-click-harvest/files/13242106/rightclickharvest-error.txt)

**Comment by Jamalam360** [comment]
You probably need to update JamLib

**Comment by allmightychaos** [comment]
Aight, I'll try it tomorrow. Thanks for the help! 😃

**Comment by Jamalam360** [comment]
Assuming fixed, feel free to reopen if that isn't the case
