### ISSUE TITLE
[Forge] Universal Bone Meal + Right Click Harvest can cause duplicating sugar cane

### ISSUE THREAD

**Issue by PlayfulPiano** [JamCoreModding/right-click-harvest#54]
https://github.com/Fuzss/universalbonemeal/issues/6

**Comment by Jamalam360** [comment]
I can fix this once universalbonemeal updates to 1.20.2, I've chosen not to maintain versions lower than that except for critical bugs at this time

**Comment by Jamalam360** [comment]
This might be fixed, I don't remember the cause but I recently changed some sugarcane code around

**Comment by Jamalam360** [comment]
Assuming it is, please reopen if not
