### ISSUE TITLE
ERROR when attempting to launch

### ISSUE THREAD

**Issue by IDemandDonuts** [JamCoreModding/right-click-harvest#56]
When trying to launch the server with the mod I get this error message and it refuses to launch

[14:49:45] [main/WARN]: Reference map 'common-common-refmap.json' for rightclickharvest.mixins.json could not be read. If this is a development environment you can ignore this message

it does look like another message comes before closing but it's only there for a single frame before it closes.

I'm using latest version for 1.20.2 java, I'm also using latest version for fabric api and that other dependency that i can't remember the spelling for.

**Comment by Jamalam360** [comment]
This is a non-fatal issue, so there'll be another error. Please send your latest.log

**Comment by IDemandDonuts** [comment]
[latest.log](https://github.com/JamCoreModding/right-click-harvest/files/13453478/latest.log)

Sorry it took so long, I hope this helps you

**Comment by Jamalam360** [comment]
Install the latest version of jamlib. It should be listed in the dependencies section on curseforge and modrinth

**Comment by IDemandDonuts** [comment]
Mother of Luna, I am so sorry. I must've uninstalled it by mistake. You have a wonderful day
