### ISSUE TITLE
Update to support Minecraft 1.20.4 Fabric

### ISSUE THREAD

**Issue by lospejos** [JamCoreModding/right-click-harvest#57]
Please update to support Minecraft 1.20.4 Fabric. Thanks!

**Comment by triphora** [comment]
If you read the [latest version changelog](https://github.com/JamCoreModding/right-click-harvest/releases/tag/4.0.2%2B1.20.2), you would know that it says...
> 1.20.4 will come soon

**Comment by Jamalam360** [comment]
That's right, 1.20.4 will come once I have updated all my mods to support NeoForge on 1.20.2. Should be done by the end of this weekend
