### ISSUE TITLE
Duplicating crop when using havest with radius

### ISSUE THREAD

**Issue by lnminh1411** [JamCoreModding/right-click-harvest#60]
Version: Fabric 1.20.4 / v4.1.3

Recreation:
Using a hoe (gold and above) and harvest wheat, the crop that is clicked will be duplicate.
Settings:
Harvest with radius: Yes

Mods installed:
Mod menu
RightClickHarvest
Fabric API (Newest)

**Comment by Jamalam360** [comment]
Thank you for reporting, I can reproduce this and it will be fixed soon
