### ISSUE TITLE
[Fabric 1.20.1] Right click does not work with the hoe from the other mod

### ISSUE THREAD

**Issue by AlexGBRV** [JamCoreModding/right-click-harvest#62]
RightClickHarvest does not work with the copper hoe from this mod: [https://www.curseforge.com/minecraft/mc-mods/copper-equipment](url). Am I understanding correctly that RightClickHarvest only works with vanilla hoes?

**Comment by Jamalam360** [comment]
If you're comfortable with creating datapacks: https://docs.jamalam.tech/right-click-harvest/tags/

Otherwise, you can ask the Dev of copper equipment to add those tags.

It's probably a bug that untagged hoes don't work even if they're a HoeItem though, so I'll fix that at some point

**Comment by AlexGBRV** [comment]
Thanks for the answer! Looks like there really is a problem with the tags.
