### ISSUE TITLE
[Feature] Add config for AoE for with and without hoe

### ISSUE THREAD

**Issue by NielsPilgaard** [JamCoreModding/right-click-harvest#65]
Hi 👋 

I would like to configure the following:

- Right-click without hoe harvests and replants the plant you're looking at (equal to setting both configs to `false`)
- Right-click with hoe harvests and replants in an area - ideally taking a bit of hunger as "payment"

I hope you'll consider it 😊

**Comment by Jamalam360** [comment]
This is already how the mod behaves, unless I misunderstand you.

**Comment by Jamalam360** [comment]
Oh no, I guess not when re-reading it. I'm not sure it will be implemented, since it might make the config too confusing. Thanks anyways

**Comment by NielsPilgaard** [comment]
That's fair, thanks for reading 👍
