### ISSUE TITLE
Neoforge 21.0.40+ compatability issue

### ISSUE THREAD

**Issue by Kevin-Marsh** [JamCoreModding/right-click-harvest#67]
ToolActions were renamed to ItemAbilities in Neoforge 21.0.40-beta. This prevents right click harvest from functioning on 40+ versions.

**Comment by Jamalam360** [comment]
Will be updated once architectury supports these newer betas. For now you'll have to hold off on upgrading

**Comment by Jamalam360** [comment]
Now updated
