### ISSUE TITLE
crashes with error code 1

### ISSUE THREAD

**Issue by queermeet-dev** [JamCoreModding/right-click-harvest#68]
I installed the mod and the dependencies, game crashes with error code 1

Log is attached

[latest.log](https://github.com/user-attachments/files/16119825/latest.log)

**Comment by Jamalam360** [comment]
I can't see an error in this log, and also debugging issues with Optifabric included is difficult and unsupported. Please reopen if you have a different log or can reliably reproduce the issue without Optifabric
