### ISSUE TITLE
Thank you for the mod!

### ISSUE THREAD

**Issue by AlexKVal** [JamCoreModding/right-click-harvest#72]
Hi @Jamalam360 👋 

Thank you for this nice handy mod 🙏
I've been using it to learn the MC-modding (for both (Neo)Forge and Fabric) and Java language.

Here are the results of my learning. Feel free to use them if you like the result in any way :)

https://github.com/AlexKVal/right-click-harvest/pull/1 some code refactoring to better understand the structure of the mod. The 'static-only methods' way is preserved. The tests are green. Everything works as before, including the different configuration settings combinations.

https://github.com/AlexKVal/right-click-harvest/pull/2 the migration to the 'use Classes' way. I like this one, b/c now many methods could be "mixed in" in the MC classes by making the code to (arguably :)) even easier to understand and expand.
As a bonus, one small (insufficient) bug is fixed along the way, and it is easy to expand the radius-harvesting to the Sugar Cane and Cactus as starting blocks. That would be just "one method swap" change (details in the PR comment)

For both branches, I preserved the commits that I was making, so it is easy to see what change and why is done to follow all the path :)

**Comment by Jamalam360** [comment]
Hi, sorry it's taken me sooooo long to look at this, I'm very busy. The change to use OOP with the `BaseHarvester` class is definitely interesting, but I don't have time to look through it properly still haha.

One thing I will say, `HarvestContext` does serve a use - it means that if I want to add another parameter, it's not a breaking change for API users.

Anyway, seems like you're doing well at learning mc modding, good luck!
