### ISSUE TITLE
Please change the mod so that it is compatible with modded hoes

### ISSUE THREAD

**Issue by ShadowDragon1848** [JamCoreModding/right-click-harvest#73]
I have to admit, I have not much knowledge about modding. But is it possible to make the mod compatible with "More Useful Copper" (and maybe other modded hoes)?

**Comment by Jamalam360** [comment]
The hoes need to be added to one of the item tags listed here: https://docs.jamalam.tech/right-click-harvest/tags.

This is generally something you would do using a datapack, or the More Useful Copper devs would do on their side.
