### ISSUE TITLE
Farmer's Delight tomato plant bug - MC 1.21 - Mod ver. 4.3.1

### ISSUE THREAD

**Issue by Rycanist** [JamCoreModding/right-click-harvest#75]
When harvesting tomatoes from Farmer's Delight, the ropes that helps extend the plant ends up getting deleted. The plant will end up breaking itself after a block update.

edit: forgot to mention its on NeoForge 21.1.37

**Comment by Jamalam360** [comment]
Thank you both for reporting, should be fixed in the latest versions
