### ISSUE TITLE
Incompatible mods - Version mismatch (Modrinth App) 1.21

### ISSUE THREAD

**Issue by Unleashed75** [JamCoreModding/right-click-harvest#79]
With only these mods installed - for testing.
architectury-13.0.8-fabric.jar   -   I didn't add this into the test myself so, I guess it's needed by RightClickHarvest.
fabric-api-0.102.0+1.21.jar
jamlib-fabric-1.2.2+1.21.1.jar
rightclickharvest-fabric-4.4.3+1.21.1.jar

All these mods are listed as being the latest mods for version 1.21 - not 1.21.1 or newer
JamLib has to be rolled back to;
jamlib-fabric-1.2.1+1.21.jar before it works with fabric and
RightClickHarvest has to be rolled back further to;
rightclickharvest-fabric-4.3.1+1.21.jar

These tests were done using the Modrinth App and all listed mods where correct at the time on both, the app and their website.
Again all these mods are listed to work for MC 1.21
I'm guessing this is just an oversite on the metadata for compactable versions.

Do I need to report the same issue for JamLib or is it part of your mods and can be update from here without a extra report being made?

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric-api) 0.102.0+1.21 with mod 'Fabric API' (fabric-api), version 0.106.0+1.21.1 or later.
More details:
	 - Mod 'JamLib' (jamlib) 1.2.2+1.21.1 requires version 0.106.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!
	 - Mod 'Right Click Harvest' (rightclickharvest) 4.4.3+1.21.1 requires version 0.106.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Jamalam360** [comment]
Fixed in latest update
